services:
  nexus:
    build:
      context: .
      dockerfile: ./Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"
      tags:
        - ghcr.io/focuseddevs/nexus-repository-composer:latest
        - nexus-repository-composer:latest

    image: ghcr.io/focuseddevs/nexus-repository-composer:latest
    ports:
      - "8081:8081"
    volumes:
      - ./nexus-data:/nexus-data